id: P010769
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16785
  title: བོད་བརྒྱུད་ནང་བསྟན་སྔ་འགྱུར་བཀའ་གཏེར་དཀྱིལ་འཁོར་དཔེ་རིས།
  author: ''
  volumes:
    1e4b451f1bba479db39e89680580edd3:
      image_group_id: I1KG16888
      title: ''
      volume_number: 1
      total_pages: 252
      base_file: v001.txt
